"use client";

import { useState } from "react";

export interface ReportWard {
  full_name: string;
  classLabel: string;
  programme: string | null;
  study_label: string;
  lessons_done: number;
  streak_days: number;
}

export interface ReportSubject {
  subject: string;
  score: number;
}

export default function ParentReportButton({
  ward,
  subjects,
  focusAreas,
}: {
  ward: ReportWard;
  subjects: ReportSubject[];
  focusAreas: ReportSubject[];
}) {
  const [done, setDone] = useState(false);

  function downloadReport() {
    const today = new Date().toISOString().slice(0, 10);
    const avg = subjects.length
      ? Math.round(subjects.reduce((a, s) => a + s.score, 0) / subjects.length)
      : 0;

    const lines: string[] = [
      "PhorLearn SHS — Full Progress Report",
      "====================================",
      `Student: ${ward.full_name}`,
      `Class: ${ward.classLabel} ${ward.programme ?? ""}`.trim(),
      `Generated: ${today}`,
      "",
      "Weekly activity",
      "---------------",
      `Study time: ${ward.study_label}`,
      `Lessons completed: ${ward.lessons_done}`,
      `Current streak: ${ward.streak_days} days`,
      "",
      "Subject performance",
      "-------------------",
      ...subjects.map((s) => `  ${s.subject}: ${s.score}%`),
      "",
      `Average score: ${avg}%`,
      "",
      focusAreas.length
        ? `Needs attention: ${focusAreas.map((s) => `${s.subject} (${s.score}%)`).join(", ")}`
        : "No subjects currently below the 65% focus threshold. Great work!",
      "",
      "Generated by PhorLearn SHS.",
    ];

    const blob = new Blob([lines.join("\n")], {
      type: "text/plain;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const safeName = ward.full_name.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
    a.download = `progress-report-${safeName}-${today}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setDone(true);
    window.setTimeout(() => setDone(false), 2500);
  }

  return (
    <button
      type="button"
      onClick={downloadReport}
      className="rounded-lg border-2 border-line py-2.5 text-muted transition hover:border-brand hover:text-brand"
    >
      <span aria-hidden="true">📋 </span>
      {done ? "Report downloaded ✓" : "Full Report"}
    </button>
  );
}
